apiVersion: v1
kind: LimitRange
metadata:
  name: store-limit-range
  namespace: {{ .Values.namespace.name }}
spec:
  limits:
  - type: Container
    default:
      cpu: {{ .Values.limitRange.defaultCpu }}
      memory: {{ .Values.limitRange.defaultMemory }}
    max:
      cpu: {{ .Values.limitRange.maxCpu }}
      memory: {{ .Values.limitRange.maxMemory }}
