{{- if not (lookup "v1" "Namespace" "" .Values.namespace.name) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: woocommerce-store
    app.kubernetes.io/instance: {{ .Values.storeName }}
    store-id: {{ .Values.storeId }}
    pod-security.kubernetes.io/enforce: baseline
{{- end }}
