apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: store-rolebinding
  namespace: {{ .Values.namespace.name }}
subjects:
- kind: ServiceAccount
  name: store-sa
  namespace: {{ .Values.namespace.name }}
roleRef:
  kind: Role
  name: store-role
  apiGroup: rbac.authorization.k8s.io
