apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: store-role
  namespace: {{ .Values.namespace.name }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "secrets", "persistentvolumeclaims", "configmaps"]
  verbs: ["get", "list", "watch"]
