apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  root-password: {{ .Values.mysql.rootPassword }}
  user: {{ .Values.mysql.user }}
  password: {{ .Values.mysql.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  auth-key: {{ .Values.wordpress.salts.authKey }}
  secure-auth-key: {{ .Values.wordpress.salts.secureAuthKey }}
  logged-in-key: {{ .Values.wordpress.salts.loggedInKey }}
  nonce-key: {{ .Values.wordpress.salts.nonceKey }}
  auth-salt: {{ .Values.wordpress.salts.authSalt }}
  secure-auth-salt: {{ .Values.wordpress.salts.secureAuthSalt }}
  logged-in-salt: {{ .Values.wordpress.salts.loggedInSalt }}
  nonce-salt: {{ .Values.wordpress.salts.nonceSalt }}
