apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      serviceAccountName: store-sa
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
        fsGroup: 0
      containers:
      - name: wordpress
        image: {{ .Values.wordpress.image }}
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql:3306
        - name: WORDPRESS_DB_NAME
          value: {{ .Values.mysql.database }}
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: WORDPRESS_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: auth-key
        - name: WORDPRESS_SECURE_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: secure-auth-key
        - name: WORDPRESS_LOGGED_IN_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: logged-in-key
        - name: WORDPRESS_NONCE_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: nonce-key
        - name: WORDPRESS_AUTH_SALT
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: auth-salt
        - name: WORDPRESS_SECURE_AUTH_SALT
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: secure-auth-salt
        - name: WORDPRESS_LOGGED_IN_SALT
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: logged-in-salt
        - name: WORDPRESS_NONCE_SALT
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: nonce-salt
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
        resources:
          {{ toYaml .Values.wordpress.resources | nindent 10 }}
        startupProbe:
          tcpSocket:
            port: 80
          failureThreshold: 60
          periodSeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 6
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 6
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - FOWNER
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
