apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-worker
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-worker
  template:
    metadata:
      labels:
        app: platform-worker
    spec:
      serviceAccountName: platform-ops
      containers:
        - name: worker
          image: asia-south1-docker.pkg.dev/urumi-487318/urumi/backend:latest
          command:
            - celery
            - -A
            - app.tasks.celery_app.celery_app
            - worker
            - -l
            - info
          envFrom:
            - configMapRef:
                name: platform-config
            - secretRef:
                name: platform-secrets
          env:
            - name: APP_HELM_CHART_PATH
              value: /app/helm/woocommerce-store
